spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.32.22/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=JgbiNLx3KN0r6i6X2mf3nAcB
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:GcY2OZmLNuTBdSgq1L7AJvBw@172.21.95.18/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 
